Import('env')
env = env.Clone()

env.ParseConfig('pkg-config sdl2 --cflags --libs')
env.ParseConfig('pkg-config SDL2_image --cflags --libs')

env.SharedLibrary('mng', [
    'engine.c',
    'engine_core.c',
    'game.c',
    'math.c',
    'point2.c',
    'random.c',
    'rect.c',
    'renderer.c',
    'resources.c',
    'size.c',
    'sprite.c',
    'texture.c',
    'timer.c',
    'vector2.c',
    'window.c',
])
